class ConsultaOEDB {
  static const String oesTableSql = 'CREATE TABLE OES('
      ' idEjecucion TEXT PRIMARY KEY,'
      ' descripcionEjecucion TEXT,'
      ' fechaEjecucion TEXT,'
      ' idUser TEXT,'
      ' idPerson TEXT,'
      ' nameCreated TEXT,'
      ' surmaneCreated TEXT,'
      ' dniCreated TEXT,'
      ' idEmpresa TEXT,'
      ' nombreEmpresa TEXT,'
      ' rucEmpresa TEXT,'
      ' idDepartamento TEXT,'
      ' nombreDepartamento TEXT,'
      ' idSede TEXT,'
      ' nombreSede TEXT)';

  static const String posTableSql = 'CREATE TABLE POS('
      ' idPOS TEXT PRIMARY KEY,'
      ' fechaServicio TEXT,'
      ' fechaFin TEXT,'
      ' idEmpresa TEXT,'
      ' nombreEmpresa TEXT,'
      ' rucEmpresa TEXT,'
      ' direccionEmpresa TEXT,'
      ' departamentoEmpresa TEXT,'
      ' provinciaEmpresa TEXT,'
      ' distritoEmpresa TEXT,'
      ' idDepartamento TEXT,'
      ' nombreDepartamento TEXT,'
      ' idSede TEXT,'
      ' nombreSede TEXT,'
      ' idVehiculo TEXT,'
      ' placaVehiculo TEXT,'
      ' idUser TEXT,'
      ' idPerson TEXT,'
      ' nameCreated TEXT,'
      ' surmaneCreated TEXT,'
      ' dniCreated TEXT)';
}
