class LogisticaDB {
  static const String proveedoresTableSql = 'CREATE TABLE Proveedores('
      ' idProveedor TEXT PRIMARY KEY,'
      ' nombreProveedor TEXT,'
      ' rucProveedor TEXT,'
      ' direccionProveedor TEXT,'
      ' telefonoProveedor TEXT,'
      ' contactoProveedor TEXT,'
      ' emailProveedor TEXT,'
      ' clase1Proveedor TEXT,'
      ' clase2Proveedor TEXT,'
      ' clase3Proveedor TEXT,'
      ' clase4Proveedor TEXT,'
      ' clase5Proveedor TEXT,'
      ' clase6Proveedor TEXT,'
      ' banco1Proveedor TEXT,'
      ' banco2Proveedor TEXT,'
      ' banco3Proveedor TEXT,'
      ' estadoProveedor TEXT)';

  static const String ordenPedidoTableSql = 'CREATE TABLE OrdenPedido('
      ' idOP TEXT PRIMARY KEY,'
      ' numeroOP TEXT,'
      ' nombreEmpresa TEXT,'
      ' nombreSede TEXT,'
      ' idProveedor TEXT,'
      ' nombreProveedor TEXT,'
      ' monedaOP TEXT,'
      ' totalOP TEXT,'
      ' fechaOP TEXT,'
      ' nombrePerson TEXT,'
      ' surnamePerson TEXT,'
      ' surname2Person TEXT,'
      ' nombreApro TEXT,'
      ' surnameApro TEXT,'
      ' surname2Apro TEXT,'
      ' fechaCreacion TEXT,'
      ' estado TEXT,'
      ' departamento TEXT,'
      ' condicionesOP TEXT,'
      ' rucProveedor TEXT,'
      ' opVencimiento TEXT,'
      ' rendido TEXT)';

  static const String detalleOrdenPedidoTableSql = 'CREATE TABLE DetalleOrdenPedido('
      ' idDetalleOP TEXT PRIMARY KEY,'
      ' idOP TEXT,'
      ' idDetalleSI TEXT,'
      ' precioUnitario TEXT,'
      ' precioTotal TEXT,'
      ' idSI TEXT,'
      ' idRecurso TEXT,'
      ' idTipoRecurso TEXT,'
      ' descripcionSI TEXT,'
      ' umSI TEXT,'
      ' cantidadSI TEXT,'
      ' estadoSI TEXT,'
      ' atentidoSI TEXT,'
      ' cajaAlmacenSI TEXT,'
      ' tipoNombreRecurso TEXT,'
      ' nroSI TEXT,'
      ' logisticaNombreRecurso TEXT)';

  static const String recursosAlmacenTableSql = 'CREATE TABLE RecursosAlmacen('
      ' idAlmacen TEXT PRIMARY KEY,'
      ' idSede TEXT,'
      ' idRecursoLogistica TEXT,'
      ' idTipoRecurso TEXT,'
      ' unidadAlmacen TEXT,'
      ' stockAlmacen TEXT,'
      ' descripcionAlmacen TEXT,'
      ' ubicacionAlmacen TEXT,'
      ' idClaseLogistica TEXT,'
      ' nombreRecurso TEXT,'
      ' unidadRecurso TEXT,'
      ' idTipoLogistica TEXT,'
      ' nombreClaseLogistica TEXT,'
      ' nombreTipoLogistica TEXT,'
      ' nombreTipoRecurso TEXT,'
      ' estadoTipoRecurso TEXT)';

  static const String dniPersonalAlmacenTableSql = 'CREATE TABLE DNIPersonalAlmacen('
      ' dni TEXT PRIMARY KEY,'
      ' name TEXT,'
      ' surname TEXT,'
      ' surname2 TEXT)';

  static const String recursoLogisticaTableSql = 'CREATE TABLE RecursoLogistica('
      ' idRecursoLogistica TEXT PRIMARY KEY,'
      ' idSede TEXT,'
      ' nombreClaseLogistica TEXT,'
      ' nombreRecursoLogistica TEXT,'
      ' cantidadAlmacen TEXT)';

  static const String notasPendientesTableSql = 'CREATE TABLE NotasPendientes('
      ' idAlmacenLog TEXT PRIMARY KEY,'
      ' idSede TEXT,'
      ' codigoAlmacenLog TEXT,'
      ' tipoAlmacenLog TEXT,'
      ' comentarioAlmacenLog TEXT,'
      ' dniSoliAlmacenLog TEXT,'
      ' nombreSoliAlmacenLog TEXT,'
      ' fechaAlmacenLog TEXT,'
      ' horaAlmacenLog TEXT,'
      ' aprobacionAlmacenLog TEXT,'
      ' idUserAprobacion TEXT,'
      ' estadoAlmacenLog TEXT,'
      ' entregaAlmacenLog TEXT,'
      ' horaEntregaAlmacenLog TEXT,'
      ' personaEntregaAlmacenLog TEXT,'
      ' idOPAlmacenLog TEXT,'
      ' idSIAlmacenLog TEXT,'
      ' destinoAlmacenLog TEXT,'
      ' nombreSede TEXT)';
}
