class MantenimientoDB {
  static const String checkItemInspeccionTableSql = 'CREATE TABLE CheckItemInspeccion('
      ' idCheckItemInsp TEXT PRIMARY KEY,'
      ' idCatInspeccion TEXT,'
      ' idItemInspeccion TEXT,'
      ' idVehiculo TEXT,'
      ' conteoCheckItemInsp TEXT,'
      ' descripcionCheckItemInsp TEXT,'
      ' estadoMantenimientoCheckItemInsp TEXT,'
      ' estadoCheckItemInsp TEXT,'
      ' valueCheckItemInsp TEXT,'
      ' ckeckItemHabilitado TEXT,'
      ' observacionCkeckItemInsp TEXT)';

  static const String inspeccionVehiculosTableSql = 'CREATE TABLE InspeccionVehiculos('
      ' idInspeccionVehiculo TEXT PRIMARY KEY,'
      ' fechaInspeccionVehiculo TEXT,'
      ' horaInspeccionVehiculo TEXT,'
      ' numeroInspeccionVehiculo TEXT,'
      ' estadoCheckInspeccionVehiculo TEXT,'
      ' placaVehiculo TEXT,'
      ' marcaVehiculo TEXT,'
      ' rucVehiculo TEXT,'
      ' imageVehiculo TEXT,'
      ' razonSocialVehiculo TEXT,'
      ' idchofer TEXT,'
      ' documentoChofer TEXT,'
      ' nombreChofer TEXT,'
      ' nombreUsuario TEXT,'
      ' hidrolinaVehiculo TEXT,'
      ' kilometrajeVehiculo TEXT,'
      ' estadoFinal TEXT,'
      ' observacionInspeccion TEXT,'
      ' estado TEXT,'
      ' tipoUnidad TEXT)';

  static const String inspeccionVehiculoItemTableSql = 'CREATE TABLE InspeccionVehiculoItem('
      ' idCheckItemInsp TEXT PRIMARY KEY,'
      ' idCatInspeccion TEXT,'
      ' idItemInspeccion TEXT,'
      ' idInspeccionVehiculo TEXT,'
      ' conteoCheckItemInsp TEXT,'
      ' descripcionCheckItemInsp TEXT,'
      ' estadoMantenimientoCheckItemInsp TEXT,'
      ' estadoCheckItemInsp TEXT,'
      ' valueCheckItemInsp TEXT,'
      ' ckeckItemHabilitado TEXT,'
      ' observacionCkeckItemInsp TEXT,'
      ' responsableCheckItemInsp TEXT,'
      ' atencionCheckItemInsp TEXT,'
      ' nombreCategoria TEXT,'
      ' conclusionCheckItemInsp TEXT)';

  static const String inspeccionVehiculoDetalleTableSql = 'CREATE TABLE InspeccionVehiculoDetalle('
      ' idInspeccionDetalle TEXT PRIMARY KEY,'
      ' tipoUnidad TEXT,'
      ' plavaVehiculo TEXT,'
      ' nroCheckList TEXT,'
      ' fechsInspeccion TEXT,'
      ' horaInspeccion TEXT,'
      ' idCategoria TEXT,'
      ' descripcionCategoria TEXT,'
      ' idItemInspeccion TEXT,'
      ' descripcionItem TEXT,'
      ' idInspeccionVehiculo TEXT,'
      ' estadoInspeccionDetalle TEXT,'
      ' observacionInspeccionDetalle TEXT,'
      ' estadoFinalInspeccionDetalle TEXT)';

  static const String mantenimientoCorrectivoTableSql = 'CREATE TABLE MantenimientoCorrectivo('
      ' idMantenimiento TEXT PRIMARY KEY,'
      ' idInspeccionDetalle TEXT,'
      ' responsable TEXT,'
      ' idResponsable TEXT,'
      ' estado TEXT,'
      ' diagnostico TEXT,'
      ' fechaDiagnostico TEXT,'
      ' conclusion TEXT,'
      ' dateTimeMantenimiento TEXT,'
      ' estadoFinal TEXT,'
      ' fechaFinalMantenimiento TEXT)';
}
